import { chromium, expect } from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
const root=path.resolve('.tmp/host'), vault=path.join(root,'vault');
const browser=await chromium.connectOverCDP('http://127.0.0.1:9229');
const page=browser.contexts()[0].pages()[0];page.setDefaultTimeout(15000);
assert.ok(page.url().toLowerCase().startsWith('file:///'+root.replaceAll('\\','/').toLowerCase()+'/'),'Only the isolated host is allowed');
const readState=async()=>JSON.parse(await fs.readFile(path.join(vault,'Super Productivity/.sp-sync/state.json'),'utf8'));
const absolute=relative=>path.join(vault,relative);
const results=[];
try {
  const title=`Inbox 空 notes 与多项目-${Date.now()}`;
  await page.getByText('Inbox',{exact:true}).first().click();
  await expect(page.locator('iframe')).toHaveCount(0);
  await page.locator('button').filter({has:page.locator('mat-icon').filter({hasText:/^add$/})}).last().click();
  await page.locator('textarea').fill(title);await page.locator('textarea').press('Enter');await page.keyboard.press('Escape');
  await page.getByText(/^(?:Obsidian 同步|Obsidian Sync \/ Obsidian 同步)$/).click();await expect(page.locator('iframe')).toHaveCount(1);
  let ui=page.frameLocator('iframe');
  await expect(ui.getByRole('heading',{name:'把任务与笔记放在一起',exact:true})).toBeVisible();
  const frame=()=>page.frames().find(frame=>frame.parentFrame());
  const tasks=()=>frame().evaluate(()=>PluginAPI.getTasks());
  const before=await tasks(), inbox=before.find(task=>task.title===title);
  assert.equal(inbox.projectId,'INBOX_PROJECT');assert.equal(inbox.notes||'','');
  const state=await readState(), other=Object.entries(state.projects).find(([id])=>id!=='INBOX_PROJECT');assert.ok(other,'Select Inbox and another project first');
  await expect(ui.getByLabel('Inbox',{exact:true})).toBeChecked();await expect(ui.getByLabel(other[1].title,{exact:true})).toBeChecked();
  const parent=before.find(task=>task.title==='父子预计耗时回归');assert.ok(parent);
  const child=before.find(task=>task.parentId===parent.id);assert.ok(child);
  const file=absolute(state.projects[parent.projectId].directory+'/tasks.md');
  const markdown=await fs.readFile(file,'utf8');
  const minutes=child.timeEstimate===2700000?50:45;
  await fs.writeFile(file,markdown.split('\n').map(line=>line.includes(`sp:task:${child.id} `)?line.replace(/estimate \[[^\]]+\]\(<?sp-estimate-minutes::\s*[^)]+\)/,`estimate [${minutes}min](<sp-estimate-minutes:: ${minutes}>)`):line).join('\n'));
  const synchronize=async()=>{
    if(await ui.getByRole('button',{name:'恢复同步',exact:true}).count())await ui.getByRole('button',{name:'恢复同步',exact:true}).click();
    await ui.getByRole('button',{name:'立即同步',exact:true}).click();
    await expect(ui.getByRole('button',{name:'立即同步',exact:true})).toBeEnabled({timeout:120000});
    assert.deepEqual(await ui.locator('.issue').allTextContents(),[]);
    await ui.getByRole('button',{name:'暂停同步',exact:true}).click();
  };
  const started=Date.now();await synchronize();const durationMs=Date.now()-started;
  const updated=await readState();
  assert.ok(updated.notesPaths[inbox.id]);const note=updated.notesPaths[inbox.id];
  assert.ok((await fs.readFile(absolute(note),'utf8')).includes(`sp-task-id: "${inbox.id}"`));
  for(const project of ['INBOX_PROJECT',other[0]])assert.ok((await fs.readFile(absolute(updated.projects[project].directory+'/tasks.md'),'utf8')).includes('sp-project-id'));
  const after=await tasks();assert.equal(after.find(task=>task.id===parent.id).timeEstimate,minutes*60000);
  assert.ok((await fs.readFile(file,'utf8')).includes(`estimate [${minutes}min](<sp-estimate-minutes:: ${minutes}>)`));
  results.push('原生 Inbox 新建空 notes 任务、多个项目 tasks/note 文件同时导出通过');
  results.push(`父子耗时联动不再触发全局读回错误，${minutes}min 格式往返通过`);
  // Delete through the native task UI, then verify the plugin cleans only its owned note.
  await page.getByText('Inbox',{exact:true}).first().click();
  await expect(page.locator('iframe')).toHaveCount(0);
  await page.locator('task').filter({hasText:title}).click({button:'right'});
  await page.getByRole('menuitem',{name:/Delete task/}).click();
  const confirm=page.getByRole('dialog');
  await expect(confirm).toBeVisible();
  await confirm.getByRole('button',{name:'Delete',exact:true}).click();
  await expect(confirm).toHaveCount(0);
  await page.getByText(/^(?:Obsidian 同步|Obsidian Sync \/ Obsidian 同步)$/).click();await expect(page.locator('iframe')).toHaveCount(1);ui=page.frameLocator('iframe');
  await expect(ui.getByRole('heading',{name:'把任务与笔记放在一起',exact:true})).toBeVisible();
  await synchronize();const deleted=await readState();
  assert.equal((await tasks()).some(task=>task.id===inbox.id),false);
  assert.equal(await fs.stat(absolute(note)).then(()=>true,()=>false),false);
  assert.ok(await fs.stat(absolute(deleted.removed[inbox.id].note.recoveryPath)));
  assert.equal((await fs.readFile(absolute(deleted.projects.INBOX_PROJECT.directory+'/tasks.md'),'utf8')).includes(`sp:task:${inbox.id} `),false);
  results.push('原生 Delete task 后清理托管 note、保留恢复副本、不复活任务通过');
  await page.screenshot({path:path.join(root,'multi-fixed.png'),fullPage:true});
  const manifest=JSON.parse(await fs.readFile('manifest.json','utf8'));
  await fs.writeFile(path.join(root,'multi-acceptance.json'),JSON.stringify({version:manifest.version,host:'19.1.0',durationMs,at:new Date().toISOString(),results},null,2));
  console.log(results.join('\n'));console.log('sync duration (ms)',durationMs);
} finally {await browser.close();}
